version: "3.1"
services:
    elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
        restart: always
        environment:
          - xpack.security.enabled=true
          - "discovery.type=single-node"
          - ELASTIC_USERNAME=elastic
          - ELASTIC_PASSWORD=admin123
        networks:
          - elastic
        ports:
          - 9200:9200
        volumes:
          - es-data-volume:/usr/share/elasticsearch/data
    
    kibana:
        container_name: kibana-container
        image: docker.elastic.co/kibana/kibana:8.4.1
        restart: always
        environment:
           - ELASTICSEARCH_HOSTS=http://es-container:9200
          #  - KIBANA_PASSWORD=kib123
          #  - ELASTICSEARCH_PASSWORD=admin123
          #  - LICENSE=trial
          #  - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
        networks:
           - elastic
        depends_on:
           - elasticsearch
        ports:
           - 5601:5601

networks:
  elastic:
    driver: bridge

volumes:
  es-data-volume:
    driver: local    

  